### ISSUE TITLE
API Limits

### ISSUE THREAD

**Issue by pedroteles17** [GoogleCloudPlatform/pi-delivery#19]
Hello! I'm getting an error 429 ("Rate exceeded.") when using the pi-delivery API. I would like to know this limit so I can adjust my requests. Thank you!

**Comment by yuryu** [comment]
The API is a demo and it's not intended to be used to scan a lot of digits. The limits are adjusted based on overall workload of the service and not a fixed value. A typical use case would send probably a few requests per minute, and if you need more digits, consider downloading directly from the Cloud Storage bucket: https://storage.googleapis.com/pi100t/index.html
