### ISSUE TITLE
Change API digits request limit

### ISSUE THREAD

**Issue by ThiDiamond** [GoogleCloudPlatform/pi-delivery#22]
There is a challenge to find a 21 digit prime and palindromic sequence inside PI.
Changing the number of digits from 1000 to 10000 or even more would help a lot.

**Comment by yuryu** [comment]
This API is a demo and is not intended to be used to scan a lot of digits. For bulk access, consider downloading directly from the Cloud Storage bucket: https://storage.googleapis.com/pi100t/index.html
